# Add arguments for the directory and terraform plan files
CURRENT_DIRECTORY=$1
TARGET_DIRECTORY=$2
TERRAFORM_PLAN_FILENAME=$3
# CHANGE DIRECTORY INTO THE GIVEN DIRECTORY
cd $TARGET_DIRECTORY
# OBTAIN TERRAFORM PLAN FILE FROM S3
aws s3 cp s3://ccs.538094434428.cmpterraformpipeline.tfplan/$TERRAFORM_PLAN_FILENAME .
# RUN TERRAFORM INIT AND TERRAFORM APPLY WITH THE TFPLAN FILE
terraform init
terraform apply $TERRAFORM_PLAN_FILENAME
# CHANGE DIRECTORY BACK TO WORKING DIR
cd $CURRENT_DIRECTORY