# Add arguments for the directory and terraform plan files
CURRENT_DIRECTORY=$1
TARGET_DIRECTORY=$2
TERRAFORM_PLAN_FILENAME=$3
# CHANGE DIRECTORY INTO THE GIVEN DIRECTORY
cd $TARGET_DIRECTORY
# RUN TERRAFORM INIT AND TERRAFORM PLAN, OUTPUTTING TFPLAN FILE AS STANDARD
terraform init
terraform plan -out=$TERRAFORM_PLAN_FILENAME
# UPLOAD TO S3
aws s3 cp $TERRAFORM_PLAN_FILENAME s3://ccs.538094434428.cmpterraformpipeline.tfplan/
# CHANGE DIRECTORY BACK TO WORKING DIR
cd $CURRENT_DIRECTORY