CURRENT_DIRECTORY=$1
TARGET_DIRECTORY=$2
TERRAFORM_PLAN_FILENAME=$3
TERRAFORM_PLAN_S3_BUCKET_NAME=$4
cd $TARGET_DIRECTORY
aws s3 cp s3://$TERRAFORM_PLAN_S3_BUCKET_NAME/$TERRAFORM_PLAN_FILENAME .
if [ $? -ne 0 ]
then
  echo Terraform plan file not found for $TERRAFORM_PLAN_S3_BUCKET_NAME/$TERRAFORM_PLAN_FILENAME , skipping...
else
  # RUN TERRAFORM INIT AND TERRAFORM APPLY WITH THE TFPLAN FILE
  terraform init
  terraform apply $TERRAFORM_PLAN_FILENAME
fi
# CHANGE DIRECTORY BACK TO WORKING DIR
cd $CURRENT_DIRECTORY