CURRENT_DIRECTORY=$1
TARGET_DIRECTORY=$2
TERRAFORM_PLAN_FILENAME=$3
cd $TARGET_DIRECTORY
echo "Showing proposed changes for $TARGET_DIRECTORY"
terraform show $TERRAFORM_PLAN_FILENAME
cd $CURRENT_DIRECTORY