CURRENT_DIRECTORY=$1
TARGET_DIRECTORY=$2
TERRAFORM_PLAN_FILENAME=$3
TERRAFORM_PLAN_S3_BUCKET_NAME=$4
cd $TARGET_DIRECTORY
terraform init
terraform plan -out=$TERRAFORM_PLAN_FILENAME
aws s3 cp $TERRAFORM_PLAN_FILENAME s3://$TERRAFORM_PLAN_S3_BUCKET_NAME/
cd $CURRENT_DIRECTORY