version: 0.2

env:
  parameter-store:
    APP_ACCESS_CIDR_KEY: "/Sandbox/config/app_access_cidr_key"
    APP_ACCESS_CIDR_VALUE: "/Sandbox/config/app_access_cidr_value"
    DOMAIN_NAME: "/Sandbox/config/domain_name"
    DOMAIN_INTERNAL_PREFIX: "/Sandbox/config/domain_prefix"
    ENABLE_HTTPS: "/Sandbox/config/enable_https"
    SHARED_POSTCODE_DATA_BUCKET: "/Sandbox/config/shared_postcode_data_bucket"
    SSH_ACCESS_CIDR_KEY: "/Sandbox/config/ssh_access_cidr_key"
    SSH_ACCESS_CIDR_VALUE: "/Sandbox/config/ssh_access_cidr_value"

phases:

  install:
    commands:
      # install required binary for terraform
      - current_dir=$(pwd)
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      - unzip -o terraform.zip
      - cd $current_dir
      # Ensure that config.auto.tfvars is populated upon each run
      - echo app_access_cidr_key = \"$APP_ACCESS_CIDR_KEY\" >> terraform/infrastructure/config.auto.tfvars
      - echo app_access_cidr_value = \"$APP_ACCESS_CIDR_VALUE\" >> terraform/infrastructure/config.auto.tfvars
      - echo app_access_cidrs = {\"$APP_ACCESS_CIDR_KEY\" = \"$APP_ACCESS_CIDR_VALUE\"} >> terraform/infrastructure/config.auto.tfvars
      - echo domain_name = \"$DOMAIN_NAME\" >> terraform/infrastructure/config.auto.tfvars
      - echo domain_internal_prefix = \"$DOMAIN_INTERNAL_PREFIX\" >> terraform/infrastructure/config.auto.tfvars
      - echo enable_https = \"$ENABLE_HTTPS\" >> terraform/infrastructure/config.auto.tfvars
      - echo shared_postcode_data_bucket = \"$SHARED_POSTCODE_DATA_BUCKET\" >> terraform/infrastructure/config.auto.tfvars
      - echo ssh_access_cidr_key = \"$SSH_ACCESS_CIDR_KEY\" >> terraform/infrastructure/config.auto.tfvars
      - echo ssh_access_cidr_value = \"$SSH_ACCESS_CIDR_VALUE\" >> terraform/infrastructure/config.auto.tfvars
      - echo ssh_access_cidrs = {\"$SSH_ACCESS_CIDR_KEY\" = \"$SSH_ACCESS_CIDR_VALUE\"} >> terraform/infrastructure/config.auto.tfvars
      # Terraform Apply on Bootstrap Script, Targeting Only Backend Files
      - cd $BOOTSTRAP_DIR && terraform init
      - terraform apply -auto-approve -target=module.infrastructure_backend.local_file.backend-tf
      - cd $current_dir

  build:
    commands:
      - bash terraform/codepipeline/terraform_plan.sh $current_dir $INFRASTRUCTURE_DIR $INFRASTRUCTURE_TFPLAN

  post_build:
    commands:
      - echo Please check the $BOOTSTRAP_TF_PLAN for the $BOOTSTRAP_DIR directory
      - echo Please check the $INFRASTRUCTURE_TF_PLAN for the $INFRASTRUCTURE_DIR directory
