version: 0.2

phases:

  install:
    commands:
      # install required binary
      - current_dir=$(pwd)
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      - unzip -o terraform.zip
      - cd $current_dir

  build:
    commands:
      - cd $BOOTSTRAP_DIR && terraform init && terraform plan -out=../../$BOOTSTRAP_TFPLAN && cd ../../
      - cd terraform/infrastructure/ && terraform init && terraform plan -out=../../infra_tfplan

  post_build:
    commands:
      - echo Please check the $BOOTSTRAP_TF_PLAN for the $BOOTSTRAP_DIR directory

artifacts:
  files:
    - $BOOTSTRAP_TFPLAN
