version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - if [ -e CCS_VERSION ]; then export CCS_VERSION=$(cat CCS_VERSION); else export CCS_VERSION=0.0.1; fi
      - if [ -e pipeline_pre_build.sh ]; then chmod +x pipeline_pre_build.sh && . ./pipeline_pre_build.sh; else exit 0; fi
      - for SSM_ALIAS in $(aws ssm describe-parameters --query 'Parameters[?Name!=`null`]|[?(starts_with(Name, `/Environment/${container_prefix}/${container_name}/`) || starts_with(Name, `/Environment/global/`))][Name]' --output text);
        do
          SSM_ENV="$${SSM_ALIAS##*/}";
          SSM_VALUE=`aws ssm get-parameter --with-decryption --name $SSM_ALIAS --query "Parameter.Value"`;
          export $SSM_ENV="$SSM_VALUE";
        done;
  build:
    commands: 
      - ${join("\n      - ",formatlist("\"%s\"",split(",",commands)))}
  post_build:
    commands:
      - if [ -e pipeline_post_build.sh ]; then chmod +x pipeline_post_build.sh && . ./pipeline_post_build.sh; else exit 0; fi
